"""File system tools: read and write files."""
from __future__ import annotations

import json
import re
import shutil
import hashlib
import subprocess
import sys
import time as _time
from fnmatch import fnmatch
from pathlib import Path
from urllib.parse import urlparse

from hushclaw.tools.base import tool, ToolResult

_ARTIFACTS_DIRNAME = "artifacts"
_SKILL_CONTAINER_DIRS = {"skills", "user-skills", "skill-packages"}
_MARKDOWN_WATERMARK_EXTENSIONS = {".md", ".markdown"}
_MARKDOWN_WATERMARK_FOOTER = "---\n*Generated by hushclaw*"
_MARKDOWN_WATERMARK_RE = re.compile(
    r"(?:^|\n)---\s*\n\*Generated by hushclaw\*\s*$",
    re.IGNORECASE,
)
_DOCUMENT_UPDATE_EXTENSIONS = {".md", ".markdown", ".html", ".htm", ".txt"}
_DEFAULT_SEARCH_SKIP_DIRS = {
    ".git", ".hg", ".svn", ".tox", ".venv", "venv", "node_modules",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
    "dist", "build",
}
_MAX_SEARCH_FILE_BYTES = 2 * 1024 * 1024


def _looks_like_skill_definition_file(path: Path) -> bool:
    """Return True for SKILL.md files that live inside a skill container."""
    if path.name != "SKILL.md":
        return False
    return any(part.lower() in _SKILL_CONTAINER_DIRS for part in path.parts)


def _apply_markdown_watermark(path: Path, content: str) -> str:
    """Append the default footer watermark to generated Markdown documents."""
    if _looks_like_skill_definition_file(path):
        return content
    if path.suffix.lower() not in _MARKDOWN_WATERMARK_EXTENSIONS:
        return content

    normalized = content.rstrip()
    if _MARKDOWN_WATERMARK_RE.search(normalized):
        return normalized + "\n"
    if not normalized:
        return f"{_MARKDOWN_WATERMARK_FOOTER}\n"
    return f"{normalized}\n\n{_MARKDOWN_WATERMARK_FOOTER}\n"


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _validate_editable_document_path(path: str, *, _config=None, _memory_store=None, tool_name: str) -> Path | ToolResult:
    p = _resolve_read_path(path, _config=_config, _memory_store=_memory_store)
    if not p.exists():
        return ToolResult.error(
            f"Document not found: {path}. Use write_file when creating a new document."
        )
    if not p.is_file():
        return ToolResult.error(f"Not a file: {path}")
    if p.suffix.lower() not in _DOCUMENT_UPDATE_EXTENSIONS:
        return ToolResult.error(
            f"{tool_name} currently supports Markdown, HTML, and plain text only. "
            f"Unsupported extension: {p.suffix or '(none)'}"
        )
    return p


def _backup_document(p: Path, *, _config=None) -> str:
    ws_dir = getattr(getattr(_config, "agent", None), "workspace_dir", None) if _config else None
    version_root = (Path(ws_dir) if ws_dir else p.parent) / ".hushclaw" / "versions"
    file_key = hashlib.sha256(str(p).encode("utf-8")).hexdigest()[:12]
    version_dir = version_root / file_key
    version_dir.mkdir(parents=True, exist_ok=True)
    stamp = _time.strftime("%Y%m%d-%H%M%S")
    backup = version_dir / f"{stamp}-{p.name}"
    shutil.copy2(p, backup)
    return str(backup)


def _write_text_atomic(p: Path, content: str) -> None:
    tmp = p.with_name(f".{p.name}.tmp-{int(_time.time() * 1000)}")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(p)


def _normalize_ws(text: str) -> str:
    """Strip trailing whitespace from each line (preserves line count)."""
    return "\n".join(line.rstrip() for line in text.split("\n"))


def _collapse_inline_ws(text: str) -> str:
    """Normalize line-local spacing while preserving line boundaries."""
    return "\n".join(" ".join(line.strip().split()) for line in text.split("\n"))


def _normalize_markdown_table_ws(text: str) -> str:
    """Normalize Markdown table pipe spacing while preserving line boundaries."""
    lines: list[str] = []
    for line in text.split("\n"):
        collapsed = " ".join(line.strip().split())
        if "|" in collapsed:
            collapsed = re.sub(r"\s*\|\s*", "|", collapsed)
        lines.append(collapsed)
    return "\n".join(lines)


def _resolve_normalized_anchor(text: str, anchor: str, normalizer) -> tuple[int, str]:
    norm_anchor = normalizer(anchor)
    norm_text = normalizer(text)
    if not norm_anchor:
        return 0, anchor

    norm_count = norm_text.count(norm_anchor)
    if norm_count > 1:
        return norm_count, anchor
    if norm_count != 1:
        return 0, anchor

    # Both current normalizers preserve line count, so line positions are stable.
    norm_start = norm_text.index(norm_anchor)
    lines_before = norm_text[:norm_start].count("\n")
    anchor_line_count = norm_anchor.count("\n") + 1
    orig_lines = text.split("\n")
    end = lines_before + anchor_line_count
    if end <= len(orig_lines):
        resolved = "\n".join(orig_lines[lines_before:end])
        if normalizer(resolved) == norm_anchor:
            return 1, resolved
    return 0, anchor


def _find_anchor_in_text(text: str, anchor: str) -> tuple[int, str]:
    """Return (match_count, resolved_anchor) for use in patch operations.

    Tries exact match first, then conservative whitespace-normalised matches.
    The resolved_anchor is the actual substring from *text* to replace,
    which differs from *anchor* only when normalisation was applied.
    """
    # Step 1: exact
    count = text.count(anchor)
    if count > 0:
        return count, anchor

    # Step 2: strip trailing whitespace per line — handles LLM output that
    # adds/removes trailing spaces in the anchor string.
    count, resolved = _resolve_normalized_anchor(text, anchor, _normalize_ws)
    if count:
        return count, resolved

    # Step 3: collapse line-local whitespace. This handles Markdown table
    # anchors where models often add/remove spaces around cell text or pipes.
    count, resolved = _resolve_normalized_anchor(text, anchor, _collapse_inline_ws)
    if count:
        return count, resolved

    # Step 4: for Markdown tables, models frequently remove/add spaces around
    # pipe separators. Keep this scoped and uniqueness-checked.
    if "|" in anchor:
        count, resolved = _resolve_normalized_anchor(text, anchor, _normalize_markdown_table_ws)
        if count:
            return count, resolved

    return 0, anchor


def _py_syntax_errors(path: Path) -> set[str]:
    """Return syntax errors in *path* as a set of 'line:col: message' strings.

    Returns an empty set for non-Python files or if the file doesn't exist.
    Never raises; subprocess errors are silently swallowed.
    """
    if path.suffix != ".py" or not path.exists():
        return set()
    try:
        result = subprocess.run(
            [sys.executable, "-m", "py_compile", str(path)],
            capture_output=True,
            text=True,
            timeout=10,
        )
        if result.returncode == 0:
            return set()
        errors: set[str] = set()
        for line in (result.stderr or "").splitlines():
            line = line.strip()
            if line and not line.startswith("Traceback") and "SyntaxError" not in line or (
                "File" in line and "line" in line
            ):
                errors.add(line)
        # Fallback: just return stderr as single entry if parsing found nothing
        if not errors and result.stderr:
            errors.add(result.stderr.strip()[:200])
        return errors
    except Exception:
        return set()


def _build_document_update_payload(
    p: Path,
    *,
    old_sha: str,
    new_sha: str,
    backup_path: str,
    change_summary: str,
    _memory_store=None,
    lint_warnings: list[str] | None = None,
) -> ToolResult:
    file_id = ""
    url = ""
    if _memory_store is not None:
        file_id = _register_generated_file(p, _memory_store)
        url = f"/files/{file_id}" if file_id else ""

    payload = {
        "path": str(p),
        "bytes": p.stat().st_size,
        "old_sha256": old_sha,
        "new_sha256": new_sha,
        "backup_path": backup_path,
        "change_summary": change_summary,
    }
    if file_id:
        payload["file_id"] = file_id
        payload["url"] = url
    if lint_warnings:
        payload["lint_warnings"] = lint_warnings
    return ToolResult.ok(json.dumps(payload, ensure_ascii=False))


def _resolve_files_url_path(path: str, *, _memory_store=None) -> Path | None:
    """Resolve a served /files/{file_id} URL back to its stored local file."""
    if not path.startswith("/files/") or _memory_store is None:
        return None
    file_id = path.removeprefix("/files/").strip("/").split("/", 1)[0]
    if not file_id:
        return None
    conn = getattr(_memory_store, "conn", None)
    if conn is None:
        return None
    try:
        row = conn.execute(
            """
            SELECT fb.storage_path
            FROM uploaded_files uf
            JOIN file_blobs fb ON fb.blob_id = uf.blob_id
            WHERE uf.file_id = ? AND uf.deleted = 0
            """,
            (file_id,),
        ).fetchone()
    except Exception:
        return None
    if row is None:
        return None
    storage_path = row["storage_path"] if hasattr(row, "keys") else row[0]
    if not storage_path:
        return None
    return Path(storage_path).expanduser()


def _build_absolute_url(rel_url: str, _config=None) -> str:
    """Return an absolute public URL when configured."""
    base_url = ""
    if _config is not None:
        base_url = str(getattr(_config.server, "public_base_url", "") or "").strip()
    if not base_url:
        return ""
    parsed = urlparse(base_url)
    if parsed.scheme not in ("http", "https") or not parsed.netloc:
        return ""
    return f"{base_url.rstrip('/')}{rel_url}"


def _normalize_relative_path(path: str | Path, *, field_name: str) -> str:
    """Normalize a relative artifact path and reject traversal."""
    rel = Path(path)
    if rel.is_absolute() or ".." in rel.parts:
        raise ValueError(f"Invalid {field_name}: {path}")
    rel_posix = rel.as_posix().strip("/")
    if not rel_posix:
        raise ValueError(f"Invalid {field_name}: {path}")
    return rel_posix


def _build_artifact_meta(
    artifact_id: str,
    *,
    kind: str,
    name: str,
    relative_path: str,
    _config=None,
) -> dict:
    """Build normalized artifact metadata for web UI consumption."""
    rel_path = _normalize_relative_path(relative_path, field_name="artifact path")
    root_url = f"/files/{_ARTIFACTS_DIRNAME}/{artifact_id}/"
    rel_url = f"{root_url}{rel_path}"
    meta = {
        "trusted": True,
        "kind": kind,
        "url": rel_url,
        "name": name,
        "artifact_id": artifact_id,
        "file_id": artifact_id,
        "root_url": root_url,
    }
    if kind == "directory":
        meta["entry_url"] = rel_url
        meta["entry_name"] = Path(rel_path).name
    absolute_url = _build_absolute_url(rel_url, _config=_config)
    if absolute_url:
        meta["absolute_url"] = absolute_url
        absolute_root = _build_absolute_url(root_url, _config=_config)
        if absolute_root:
            meta["absolute_root_url"] = absolute_root
        if kind == "directory":
            meta["absolute_entry_url"] = absolute_url
    return meta


def _get_upload_dir(_config) -> Path:
    upload_dir: Path | None = None
    if _config is not None:
        upload_dir = getattr(_config.server, "upload_dir", None)
    if upload_dir is None:
        raise ValueError("upload_dir not configured — cannot generate artifact URL")
    upload_dir = Path(upload_dir)
    upload_dir.mkdir(parents=True, exist_ok=True)
    return upload_dir


def _get_artifacts_dir(_config) -> Path:
    artifacts_dir = _get_upload_dir(_config) / _ARTIFACTS_DIRNAME
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    return artifacts_dir


def _reuse_directory_artifact(src_dir: Path, artifacts_dir: Path, entrypoint: str) -> dict | None:
    """Return existing artifact coordinates when src_dir already lives under artifacts."""
    try:
        rel = src_dir.resolve().relative_to(artifacts_dir.resolve())
    except Exception:
        return None
    if len(rel.parts) != 1:
        return None
    artifact_id = rel.parts[0]
    entry_rel = _normalize_relative_path(entrypoint, field_name="artifact entrypoint")
    return {
        "artifact_id": artifact_id,
        "relative_path": entry_rel,
    }


def _reuse_file_artifact(src: Path, artifacts_dir: Path) -> dict | None:
    """Return existing artifact coordinates when src already lives under artifacts."""
    try:
        rel = src.resolve().relative_to(artifacts_dir.resolve())
    except Exception:
        return None
    if len(rel.parts) < 2:
        return None
    artifact_id = rel.parts[0]
    rel_path = Path(*rel.parts[1:]).as_posix()
    return {
        "artifact_id": artifact_id,
        "relative_path": rel_path,
    }


def register_download_bundle(path: str | Path, _config=None, entrypoint: str = "index.html",
                             display_name: str = "") -> dict:
    """Copy a local directory into upload_dir/artifacts and return an entry URL."""
    from uuid import uuid4

    src_dir = Path(path).expanduser()
    if not src_dir.exists():
        raise FileNotFoundError(f"Path not found: {src_dir}")
    if not src_dir.is_dir():
        raise NotADirectoryError(f"Not a directory: {src_dir}")

    entry_rel = _normalize_relative_path(entrypoint, field_name="artifact entrypoint")

    src_entry = src_dir / entry_rel
    if not src_entry.exists() or not src_entry.is_file():
        raise FileNotFoundError(f"Artifact entrypoint not found: {src_entry}")

    artifacts_dir = _get_artifacts_dir(_config)

    reused = _reuse_directory_artifact(src_dir, artifacts_dir, entry_rel)
    if reused is not None:
        return _build_artifact_meta(
            reused["artifact_id"],
            kind="directory",
            name=display_name or src_dir.name,
            relative_path=reused["relative_path"],
            _config=_config,
        )

    artifact_id = uuid4().hex[:12]
    dest_root = artifacts_dir / artifact_id
    shutil.copytree(src_dir, dest_root)
    return _build_artifact_meta(
        artifact_id,
        kind="directory",
        name=display_name or src_dir.name,
        relative_path=entry_rel,
        _config=_config,
    )


def register_download_path(path: str | Path, _config=None, display_name: str = "") -> dict:
    """Register a file or directory artifact and return normalized metadata."""
    from uuid import uuid4

    src = Path(path).expanduser()
    if not src.exists():
        raise FileNotFoundError(f"Path not found: {src}")
    if src.is_dir():
        # Pick the best entrypoint: prefer index.html, fall back to first file.
        entrypoint = "index.html"
        if not (src / entrypoint).is_file():
            first = next((f for f in sorted(src.rglob("*")) if f.is_file()), None)
            if first is None:
                raise FileNotFoundError(f"Directory is empty, cannot register as artifact: {src}")
            entrypoint = first.relative_to(src).as_posix()
        return register_download_bundle(src, _config=_config, display_name=display_name, entrypoint=entrypoint)
    if not src.is_file():
        raise IsADirectoryError(f"Not a file: {src}")

    artifacts_dir = _get_artifacts_dir(_config)

    reused = _reuse_file_artifact(src, artifacts_dir)
    if reused is not None:
        return _build_artifact_meta(
            reused["artifact_id"],
            kind="file",
            name=display_name or src.name,
            relative_path=reused["relative_path"],
            _config=_config,
        )

    safe_name = re.sub(r"[^\w.\-]", "_", display_name or src.name)[:128] or "file"
    artifact_id = uuid4().hex[:12]
    dest_root = artifacts_dir / artifact_id
    dest_root.mkdir(parents=True, exist_ok=True)
    dest = dest_root / safe_name
    shutil.copy2(src, dest)
    return _build_artifact_meta(
        artifact_id,
        kind="file",
        name=safe_name,
        relative_path=safe_name,
        _config=_config,
    )


def _read_pdf(p: Path, max_chars: int) -> tuple[str, bool]:
    import pdfplumber  # type: ignore
    parts = []
    with pdfplumber.open(str(p)) as pdf:
        for pg in pdf.pages:
            t = pg.extract_text()
            if t:
                parts.append(t)
    text = "\n\n".join(parts)
    return text[:max_chars], len(text) > max_chars


def _read_word(p: Path, max_chars: int) -> tuple[str, bool]:
    from docx import Document  # type: ignore
    doc = Document(str(p))
    text = "\n".join(para.text for para in doc.paragraphs if para.text.strip())
    return text[:max_chars], len(text) > max_chars


def _read_excel(p: Path, max_chars: int) -> tuple[str, bool]:
    from openpyxl import load_workbook  # type: ignore
    wb = load_workbook(str(p), read_only=True, data_only=True)
    parts = []
    for name in wb.sheetnames:
        ws = wb[name]
        rows = []
        for row in ws.iter_rows(values_only=True):
            row_str = "\t".join(str(c) if c is not None else "" for c in row)
            if row_str.strip():
                rows.append(row_str)
        if rows:
            parts.append(f"[Sheet: {name}]\n" + "\n".join(rows))
    text = "\n\n".join(parts)
    return text[:max_chars], len(text) > max_chars


def _resolve_read_path(path: str, *, _config=None, _memory_store=None) -> Path:
    """Resolve a user/model-supplied path using read-friendly workspace fallbacks."""
    files_url_path = _resolve_files_url_path(path, _memory_store=_memory_store)
    if files_url_path is not None:
        return files_url_path

    p = Path(path).expanduser()
    if p.is_absolute() or p.exists():
        return p

    ws_dir = getattr(getattr(_config, "agent", None), "workspace_dir", None) if _config else None
    if ws_dir:
        ws_dir = Path(ws_dir).expanduser()
        for candidate in (ws_dir / path, ws_dir / "files" / path):
            if candidate.exists():
                return candidate

    return p


def _normalize_write_path(path: str) -> tuple[str, str]:
    """Normalize model-supplied write paths and return (path, note)."""
    if not path.startswith("/files/"):
        return path, ""

    rel = path.removeprefix("/files/").strip("/")
    rel = _normalize_relative_path(rel, field_name="/files write path")
    return rel, (
        f"Normalized WebUI URL-like path {path!r} to workspace-relative path {rel!r}. "
        "'/files/…' is the served URL namespace; writes are stored under the workspace files directory."
    )


def _resolve_search_root(path: str, *, _config=None, _memory_store=None) -> Path:
    """Resolve a search root, preferring the active workspace for the default path."""
    files_url_path = _resolve_files_url_path(path, _memory_store=_memory_store)
    if files_url_path is not None:
        return files_url_path

    ws_dir = getattr(getattr(_config, "agent", None), "workspace_dir", None) if _config else None
    if path in ("", ".") and ws_dir:
        return Path(ws_dir).expanduser()

    p = Path(path or ".").expanduser()
    if p.is_absolute() or p.exists():
        return p
    if ws_dir:
        return Path(ws_dir).expanduser() / p
    return p


def _search_file_matches(
    file_path: Path,
    query: str,
    *,
    root: Path,
    max_results: int,
    context_lines: int,
    regex: bool,
    case_sensitive: bool,
) -> list[dict]:
    try:
        if file_path.stat().st_size > _MAX_SEARCH_FILE_BYTES:
            return []
        text = file_path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return []

    flags = 0 if case_sensitive else re.IGNORECASE
    if regex:
        pattern = re.compile(query, flags)
        matcher = lambda line: pattern.search(line) is not None
    else:
        needle = query if case_sensitive else query.lower()
        matcher = lambda line: needle in (line if case_sensitive else line.lower())

    lines = text.splitlines()
    results: list[dict] = []
    for idx, line in enumerate(lines):
        if not matcher(line):
            continue
        start = max(0, idx - context_lines)
        end = min(len(lines), idx + context_lines + 1)
        try:
            rel_path = file_path.resolve().relative_to(root.resolve()).as_posix()
        except Exception:
            rel_path = str(file_path)
        results.append({
            "path": rel_path,
            "absolute_path": str(file_path),
            "line": idx + 1,
            "match": line,
            "context": [
                {"line": line_no + 1, "text": lines[line_no]}
                for line_no in range(start, end)
            ],
        })
        if len(results) >= max_results:
            break
    return results


def _iter_search_files(root: Path, file_glob: str) -> list[Path]:
    if root.is_file():
        return [root] if not file_glob or fnmatch(root.name, file_glob) else []

    files: list[Path] = []
    for p in root.rglob("*"):
        if not p.is_file():
            continue
        if any(part in _DEFAULT_SEARCH_SKIP_DIRS for part in p.parts):
            continue
        if file_glob and not fnmatch(p.name, file_glob) and not fnmatch(p.as_posix(), file_glob):
            continue
        files.append(p)
    return files


def _rg_candidate_files(
    root: Path,
    query: str,
    *,
    file_glob: str,
    regex: bool,
    case_sensitive: bool,
    max_files: int,
) -> list[Path] | None:
    if root.is_file():
        return [root]
    cmd = ["rg", "--files-with-matches", "--color", "never"]
    if not regex:
        cmd.append("--fixed-strings")
    if not case_sensitive:
        cmd.append("--ignore-case")
    if file_glob:
        cmd.extend(["--glob", file_glob])
    cmd.extend([query, str(root)])
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if proc.returncode not in (0, 1):
        return None
    paths = [Path(line) for line in proc.stdout.splitlines() if line.strip()]
    return paths[:max_files]


@tool(
    name="read_file",
    description=(
        "Read the contents of a file at the specified path. "
        "Supports plain text, Markdown, CSV, PDF, Word (.docx), and Excel (.xlsx). "
        "Binary formats are extracted to readable text automatically."
    ),
    parallel_safe=True,
)
def read_file(path: str, max_chars: int = 32768, _config=None, _memory_store=None) -> ToolResult:
    """Read a file; auto-extracts text from PDF/Word/Excel."""
    try:
        p = _resolve_read_path(path, _config=_config, _memory_store=_memory_store)
        if not p.exists():
            return ToolResult.error(f"File not found: {path}")
        if not p.is_file():
            return ToolResult.error(f"Not a file: {path}")

        ext = p.suffix.lower()

        if ext == ".pdf":
            try:
                text, truncated = _read_pdf(p, max_chars)
            except ImportError:
                return ToolResult.error("pdfplumber is not installed. Run: pip install pdfplumber")
            prefix = f"[Truncated to {max_chars} chars]\n" if truncated else ""
            return ToolResult.ok(prefix + text)

        if ext in (".docx", ".doc"):
            try:
                text, truncated = _read_word(p, max_chars)
            except ImportError:
                return ToolResult.error("python-docx is not installed. Run: pip install python-docx")
            prefix = f"[Truncated to {max_chars} chars]\n" if truncated else ""
            return ToolResult.ok(prefix + text)

        if ext in (".xlsx", ".xls", ".xlsm"):
            try:
                text, truncated = _read_excel(p, max_chars)
            except ImportError:
                return ToolResult.error("openpyxl is not installed. Run: pip install openpyxl")
            prefix = f"[Truncated to {max_chars} chars]\n" if truncated else ""
            return ToolResult.ok(prefix + text)

        # Plain text fallback (txt, md, csv, json, code, etc.)
        size = p.stat().st_size
        if size > max_chars:
            content = p.read_bytes()[:max_chars].decode("utf-8", errors="replace")
            return ToolResult.ok(f"[Truncated to {max_chars} chars]\n{content}")
        return ToolResult.ok(p.read_text(encoding="utf-8", errors="replace"))

    except PermissionError:
        return ToolResult.error(f"Permission denied: {path}")
    except Exception as e:
        return ToolResult.error(f"Failed to read {path}: {e}")


@tool(
    name="search_files",
    description=(
        "Search local files and return structured matches with line numbers and nearby context. "
        "Use this before read_file/patch_document/apply_patch when the target file or anchor "
        "is not already known. This is read-only and internally prefers ripgrep when available."
    ),
    parallel_safe=True,
)
def search_files(
    query: str,
    path: str = ".",
    file_glob: str = "",
    max_results: int = 50,
    context_lines: int = 2,
    regex: bool = False,
    case_sensitive: bool = False,
    _config=None,
    _memory_store=None,
) -> ToolResult:
    """Search files with structured JSON output."""
    try:
        query = str(query or "")
        if not query:
            return ToolResult.error("query is required.")
        root = _resolve_search_root(path, _config=_config, _memory_store=_memory_store)
        if not root.exists():
            return ToolResult.error(f"Path not found: {path}")
        if not root.is_file() and not root.is_dir():
            return ToolResult.error(f"Not a searchable file or directory: {path}")

        max_results = max(1, min(int(max_results or 50), 200))
        context_lines = max(0, min(int(context_lines or 0), 10))
        if regex:
            try:
                re.compile(query, 0 if case_sensitive else re.IGNORECASE)
            except re.error as exc:
                return ToolResult.error(f"Invalid regex query: {exc}")

        candidate_files = _rg_candidate_files(
            root,
            query,
            file_glob=file_glob,
            regex=regex,
            case_sensitive=case_sensitive,
            max_files=max_results * 2,
        )
        engine = "rg"
        if candidate_files is None:
            candidate_files = _iter_search_files(root, file_glob)
            engine = "python"

        matches: list[dict] = []
        for file_path in candidate_files:
            if len(matches) >= max_results:
                break
            matches.extend(_search_file_matches(
                file_path,
                query,
                root=root if root.is_dir() else root.parent,
                max_results=max_results - len(matches),
                context_lines=context_lines,
                regex=regex,
                case_sensitive=case_sensitive,
            ))

        payload = {
            "query": query,
            "path": str(root),
            "file_glob": file_glob,
            "engine": engine,
            "count": len(matches),
            "truncated": len(matches) >= max_results,
            "matches": matches[:max_results],
        }
        return ToolResult.ok(json.dumps(payload, ensure_ascii=False))
    except Exception as e:
        return ToolResult.error(f"Failed to search files: {e}")


@tool(
    name="write_file",
    description=(
        "Create a new file, or intentionally overwrite a file when the user asked to create "
        "or save-as. Use edit_document for edits to an existing Markdown/HTML/text document. "
        "Use a relative path (e.g. 'report.md') to write inside the active workspace's files "
        "directory — this is the preferred location for generated files. "
        "Absolute paths (~/... or /...) are also accepted for other locations. "
        "If a path starts with /files/, it is treated as a WebUI URL-like alias and "
        "normalized to a workspace-relative file path before writing. "
        "Returns the file path and a /files/ download URL so the user can access the file."
    ),
    mutating=True,
)
def write_file(path: str, content: str, _config=None, _memory_store=None) -> ToolResult:
    """Write content to a file and return a download URL."""
    try:
        original_path = path
        path, normalized_note = _normalize_write_path(path)
        p = Path(path).expanduser()
        if not p.is_absolute():
            ws_dir = getattr(getattr(_config, "agent", None), "workspace_dir", None) if _config else None
            base = Path(ws_dir) / "files" if ws_dir else Path.home() / "Downloads"
            p = base / path

        content_to_write = _apply_markdown_watermark(p, content)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content_to_write, encoding="utf-8")

        if _looks_like_skill_definition_file(p):
            return ToolResult.ok(
                f"Written {len(content_to_write)} characters to {p}\n"
                "Note: SKILL.md files are runtime skill assets, so they were not added to Files. "
                "Use remember_skill(...) when creating prompt-only skills so the registry reloads automatically."
            )

        # Auto-register as downloadable artifact when server config is available.
        if _memory_store is not None:
            try:
                file_id = _register_generated_file(p, _memory_store)
                url = f"/files/{file_id}" if file_id else ""
                msg = f"Written {len(content_to_write)} chars to {p}"
                if normalized_note:
                    msg += f"\nNote: {normalized_note}"
                if url:
                    msg += f"\nDownload: {url}"
                result = ToolResult.ok(msg)
                result.artifact_id = file_id
                return result
            except Exception:
                pass  # Fall through to plain success message if registration fails

        msg = f"Written {len(content_to_write)} characters to {p}"
        if normalized_note:
            msg += f"\nNote: {normalized_note}"
        return ToolResult.ok(msg)
    except PermissionError:
        return ToolResult.error(f"Permission denied: {original_path}")
    except Exception as e:
        return ToolResult.error(f"Failed to write {path}: {e}")


def update_document(
    path: str,
    content: str,
    change_summary: str = "",
    expected_sha256: str = "",
    create_backup: bool = True,
    _config=None,
    _memory_store=None,
) -> ToolResult:
    """Update an existing text-like document with backup and artifact refresh."""
    try:
        resolved = _validate_editable_document_path(
            path, _config=_config, _memory_store=_memory_store, tool_name="update_document"
        )
        if isinstance(resolved, ToolResult):
            return resolved
        p = resolved

        old_sha = _sha256_file(p)
        if expected_sha256 and expected_sha256 != old_sha:
            return ToolResult.error(
                "Document changed since it was read; update refused. "
                f"expected_sha256={expected_sha256}, current_sha256={old_sha}"
            )

        backup_path = ""
        if create_backup:
            backup_path = _backup_document(p, _config=_config)

        baseline_errors = _py_syntax_errors(p)
        content_to_write = _apply_markdown_watermark(p, content)
        _write_text_atomic(p, content_to_write)

        new_sha = _sha256_file(p)
        lint_delta = sorted(_py_syntax_errors(p) - baseline_errors)
        return _build_document_update_payload(
            p,
            old_sha=old_sha,
            new_sha=new_sha,
            backup_path=backup_path,
            change_summary=change_summary,
            _memory_store=_memory_store,
            lint_warnings=lint_delta or None,
        )
    except PermissionError:
        return ToolResult.error(f"Permission denied: {path}")
    except Exception as e:
        return ToolResult.error(f"Failed to update document {path}: {e}")


def _normalize_document_operations(operations: list) -> list:
    normalized: list = []
    for op in operations:
        if isinstance(op, dict):
            item = _normalize_document_operation(op)
            normalized.append(item)
        else:
            normalized.append(op)
    return normalized


def _first_non_empty_string(values: list[object]) -> str:
    for value in values:
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def _normalize_operation_type(value: str) -> str:
    op_type = (value or "").strip()
    aliases = {
        "append": "append_after",
        "append-after": "append_after",
        "appendafter": "append_after",
        "add_after": "append_after",
        "insert_after": "append_after",
        "insert-after": "append_after",
        "prepend": "prepend_before",
        "prepend-before": "prepend_before",
        "prependbefore": "prepend_before",
        "add_before": "prepend_before",
        "insert_before": "prepend_before",
        "insert-before": "prepend_before",
        "remove": "delete",
        "del": "delete",
    }
    return aliases.get(op_type.lower(), op_type)


def _normalize_document_operation(op: dict) -> dict:
    """Accept common model-generated aliases while preserving strict validation."""
    item = dict(op)

    raw_type = _first_non_empty_string([
        item.get("type"),
        item.get("op_type"),
        item.get("operation"),
        item.get("action"),
        item.get("kind"),
        item.get("edit_type"),
    ])
    op_type = _normalize_operation_type(raw_type)

    if not op_type:
        if _first_non_empty_string([item.get("after"), item.get("append_after")]):
            op_type = "append_after"
        elif _first_non_empty_string([item.get("before"), item.get("prepend_before")]):
            op_type = "prepend_before"
        elif _first_non_empty_string([item.get("old_text"), item.get("old"), item.get("find")]) and _first_non_empty_string([
            item.get("new_text"), item.get("new"), item.get("replacement")
        ]):
            op_type = "replace"
        elif _first_non_empty_string([item.get("delete"), item.get("remove")]):
            op_type = "delete"

    anchor = _first_non_empty_string([
        item.get("anchor"),
        item.get("target"),
        item.get("match"),
        item.get("old_text"),
        item.get("old"),
        item.get("find"),
        item.get("search"),
        item.get("section"),
        item.get("heading"),
        item.get("after") if op_type == "append_after" else "",
        item.get("append_after") if op_type == "append_after" else "",
        item.get("before") if op_type == "prepend_before" else "",
        item.get("prepend_before") if op_type == "prepend_before" else "",
        item.get("delete") if op_type == "delete" else "",
        item.get("remove") if op_type == "delete" else "",
    ])

    content = item.get("content", "")
    if not isinstance(content, str) or not content:
        replacement = _first_non_empty_string([
            item.get("replacement"),
            item.get("new_text"),
            item.get("new"),
            item.get("insert"),
            item.get("addition"),
            item.get("value"),
        ])
        if replacement:
            content = replacement

    if op_type:
        item["type"] = op_type
    if anchor:
        item["anchor"] = anchor
    if isinstance(content, str):
        item["content"] = content
    return item


@tool(
    name="edit_document",
    description=(
        "Edit an existing Markdown, HTML, or plain-text document. This is the preferred tool "
        "for modifying existing documents. For local edits, pass operations with anchors. "
        "For full-document rewrites, pass content and set mode='rewrite' or leave mode='auto'. "
        "Do not use write_file for existing documents unless the user explicitly asked to overwrite or save-as."
    ),
    mutating=True,
)
def edit_document(
    path: str,
    content: str = "",
    operations: list | None = None,
    mode: str = "auto",
    change_summary: str = "",
    expected_sha256: str = "",
    create_backup: bool = True,
    _config=None,
    _memory_store=None,
) -> ToolResult:
    """Model-facing document edit facade that routes to patch or rewrite."""
    ops = _normalize_document_operations(operations or [])
    content = content or ""
    mode_norm = (mode or "auto").strip().lower()
    if mode_norm not in {"auto", "patch", "rewrite"}:
        return ToolResult.error("mode must be one of: auto, patch, rewrite")
    if ops and content:
        return ToolResult.error("Pass either operations for a patch or content for a rewrite, not both.")
    if not ops and not content:
        return ToolResult.error("No document edit provided. Pass operations for a patch or content for a rewrite.")
    if mode_norm == "patch" and not ops:
        return ToolResult.error("mode='patch' requires operations.")
    if mode_norm == "rewrite" and not content:
        return ToolResult.error("mode='rewrite' requires content.")
    if ops:
        return patch_document(
            path,
            ops,
            change_summary=change_summary,
            expected_sha256=expected_sha256,
            create_backup=create_backup,
            _config=_config,
            _memory_store=_memory_store,
        )
    return update_document(
        path,
        content,
        change_summary=change_summary,
        expected_sha256=expected_sha256,
        create_backup=create_backup,
        _config=_config,
        _memory_store=_memory_store,
    )


def patch_document(
    path: str,
    operations: list,
    change_summary: str = "",
    expected_sha256: str = "",
    create_backup: bool = True,
    _config=None,
    _memory_store=None,
) -> ToolResult:
    """Patch an existing text-like document using validated unique anchors."""
    try:
        resolved = _validate_editable_document_path(
            path, _config=_config, _memory_store=_memory_store, tool_name="patch_document"
        )
        if isinstance(resolved, ToolResult):
            return resolved
        p = resolved

        if not operations:
            return ToolResult.error("No operations provided.")
        if not isinstance(operations, list):
            return ToolResult.error("operations must be a list.")

        original = p.read_text(encoding="utf-8")
        old_sha = _sha256_file(p)
        if expected_sha256 and expected_sha256 != old_sha:
            return ToolResult.error(
                "Document changed since it was read; patch refused. "
                f"expected_sha256={expected_sha256}, current_sha256={old_sha}"
            )

        supported = {"replace", "append_after", "prepend_before", "delete"}
        errors: list[str] = []
        working = original

        for i, op in enumerate(operations):
            if not isinstance(op, dict):
                errors.append(f"Operation {i}: must be an object.")
                continue
            op_type = str(op.get("type") or "").strip()
            anchor = op.get("anchor")
            content = op.get("content", "")
            if op_type not in supported:
                errors.append(
                    f"Operation {i}: unsupported type {op_type!r}; use replace, append_after, prepend_before, or delete."
                )
                continue
            if not isinstance(anchor, str) or not anchor:
                errors.append(f"Operation {i}: anchor must be a non-empty string.")
                continue
            if op_type != "delete" and not isinstance(content, str):
                errors.append(f"Operation {i}: content must be a string.")
                continue
            count, resolved_anchor = _find_anchor_in_text(working, anchor)
            if count == 0:
                errors.append(f"Operation {i}: anchor not found: {anchor[:80]!r}")
                continue
            if count > 1:
                errors.append(
                    f"Operation {i}: anchor appears {count} times; provide a more specific anchor."
                )
                continue

            if op_type == "replace":
                working = working.replace(resolved_anchor, content, 1)
            elif op_type == "append_after":
                working = working.replace(resolved_anchor, resolved_anchor + content, 1)
            elif op_type == "prepend_before":
                working = working.replace(resolved_anchor, content + resolved_anchor, 1)
            elif op_type == "delete":
                working = working.replace(resolved_anchor, "", 1)

        if errors:
            return ToolResult.error(
                "Validation failed — document was not modified:\n"
                + "\n".join(f"  • {e}" for e in errors)
            )

        if working == original:
            return ToolResult.error("Patch produced no changes; document was not modified.")

        backup_path = _backup_document(p, _config=_config) if create_backup else ""
        baseline_errors = _py_syntax_errors(p)
        content_to_write = _apply_markdown_watermark(p, working)
        _write_text_atomic(p, content_to_write)
        new_sha = _sha256_file(p)
        lint_delta = sorted(_py_syntax_errors(p) - baseline_errors)
        return _build_document_update_payload(
            p,
            old_sha=old_sha,
            new_sha=new_sha,
            backup_path=backup_path,
            change_summary=change_summary,
            _memory_store=_memory_store,
            lint_warnings=lint_delta or None,
        )
    except PermissionError:
        return ToolResult.error(f"Permission denied: {path}")
    except Exception as e:
        return ToolResult.error(f"Failed to patch document {path}: {e}")


def _register_generated_file(p: Path, memory_store) -> str:
    """Record a write_file-generated file in uploaded_files. Returns stable file_id from path hash."""
    if memory_store is None:
        return ""
    try:
        raw = p.read_bytes()
        sha256_content = hashlib.sha256(raw).hexdigest()
        # Deterministic ID from path — same path = same file_id = no fragmentation
        file_id = hashlib.sha256(str(p).encode()).hexdigest()[:12]
        artifact_url = f"/files/{file_id}"
        conn = memory_store.conn
        now = int(_time.time())
        # Upsert blob by content hash
        existing_blob = conn.execute(
            "SELECT blob_id FROM file_blobs WHERE sha256=?", (sha256_content,)
        ).fetchone()
        if existing_blob:
            blob_id = existing_blob["blob_id"]
            # Keep storage_path in sync (file may have moved)
            conn.execute(
                "UPDATE file_blobs SET storage_path=? WHERE blob_id=?",
                (str(p), blob_id),
            )
        else:
            from hushclaw.util.ids import make_id
            blob_id = make_id("b-")
            conn.execute(
                "INSERT INTO file_blobs(blob_id, sha256, storage_path, size_bytes, created) VALUES (?,?,?,?,?)",
                (blob_id, sha256_content, str(p), len(raw), now),
            )
        # Upsert uploaded_files by deterministic file_id
        exists = conn.execute(
            "SELECT 1 FROM uploaded_files WHERE file_id=?", (file_id,)
        ).fetchone()
        if not exists:
            conn.execute(
                "INSERT INTO uploaded_files(file_id, blob_id, original_name, display_name, source, artifact_url, created, last_used, deleted)"
                " VALUES (?,?,?,?,?,?,?,?,0)",
                (file_id, blob_id, p.name, p.name, "generated", artifact_url, now, now),
            )
        else:
            conn.execute(
                "UPDATE uploaded_files SET blob_id=?, last_used=?, artifact_url=? WHERE file_id=?",
                (blob_id, now, artifact_url, file_id),
            )
        conn.commit()
        return file_id
    except Exception:
        return ""  # Non-critical; never break the write


@tool(
    name="list_dir",
    description="List files and directories at a given path.",
    parallel_safe=True,
)
def list_dir(path: str = ".") -> ToolResult:
    """List directory contents."""
    try:
        p = Path(path).expanduser()
        if not p.exists():
            return ToolResult.error(f"Path not found: {path}")
        if not p.is_dir():
            return ToolResult.error(f"Not a directory: {path}")
        entries = sorted(p.iterdir(), key=lambda e: (e.is_file(), e.name))
        lines = []
        for entry in entries:
            kind = "F" if entry.is_file() else "D"
            lines.append(f"[{kind}] {entry.name}")
        return ToolResult.ok("\n".join(lines) if lines else "(empty)")
    except Exception as e:
        return ToolResult.error(f"Failed to list {path}: {e}")


@tool(
    name="make_download_url",
    description=(
        "Register a local file or directory as a downloadable / previewable artifact "
        "and return its /files/ URL."
    ),
    parallel_safe=True,
)
def make_download_url(path: str, _config=None) -> ToolResult:
    """Register a file or directory artifact and return a /files/ URL."""
    try:
        payload = register_download_path(path, _config=_config)
        return ToolResult.ok(json.dumps(payload, ensure_ascii=False))
    except Exception as e:
        return ToolResult.error(f"Failed to register artifact: {e}")


@tool(
    name="make_download_bundle",
    description=(
        "Register a local directory as a previewable artifact and return the "
        "entry-page URL. Use this when generated output depends on sibling assets."
    ),
    parallel_safe=True,
)
def make_download_bundle(path: str, entrypoint: str = "index.html", _config=None) -> ToolResult:
    """Copy a directory into upload_dir/artifacts and return its entry-page URL."""
    try:
        payload = register_download_bundle(path, _config=_config, entrypoint=entrypoint)
        return ToolResult.ok(json.dumps(payload, ensure_ascii=False))
    except Exception as e:
        return ToolResult.error(f"Failed to register artifact directory: {e}")
